steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t europe-west3-docker.pkg.dev/dummy-parisa-2023/poc-gcr-lrn-dev-euw3/quickstart-image:tag1 .
  automapSubstitutions: true
options:
  logging: CLOUD_LOGGING_ONLY
images:
- 'europe-west3-docker.pkg.dev/dummy-parisa-2023/poc-gcr-lrn-dev-euw3/quickstart-image:tag1'