steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t europe-west3-docker.pkg.dev/$PROJECT_ID/poc-gcr-lrn-dev-euw3/quickstart-image:tag1 .
  automapSubstitutions: true
images:
- 'europe-west3-docker.pkg.dev/$PROJECT_ID/poc-gcr-lrn-dev-euw3/quickstart-image:tag1'